version: '1'
services:
  mongo1:
    # Add to /etc/hosts in the local machine
    # 127.0.0.1       mongo1 mongo2 mongo3
    image: mongo:latest
    restart: 'no'
    command: mongod --bind_ip_all --port 27017
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/mongodb/db1:/data/db
